spring:
  datasource:
    url: jdbc:h2:file:./data/notification_dev;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
  flyway:
    locations: classpath:db/migration,classpath:db/devmigration

notification:
  cors:
    allowed-origin: http://localhost:3000

logging:
  level:
    com.company.notification: DEBUG
